name: ews
description: A Dart client library to access Microsoft Exchange web services. The library works against Office 365 Exchange Online as well as on premises Exchange.
version: 2.1.2
author: Dmytro Glynskyi <dmytro.glynskyi@gmail.com>
homepage: https://github.com/glynskyi/ews

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  async: ^2.8.2
  xml: ^5.3.1
  synchronized: ^3.0.0
  intl: ^0.17.0
  timezone: ^0.8.0
  uuid: ^3.0.5
  collection: ^1.15.0
  html_unescape: ^2.0.0

dev_dependencies:
  test: ^1.19.2
  pedantic: ^1.11.0